import { TrainingModule } from './training.dto';

export const TRAINING_CATALOG: TrainingModule[] = [
  // Gap-triggered courses
  {
    slug: 'food-cost-engineering',
    title: 'Menu Cost Engineering',
    description: 'Reduce food cost % without sacrificing quality',
    duration: '45 min',
    level: 'intermediate',
    triggerMetric: 'foodCostPct',
    triggerCondition: 'above_peer_avg',
    tags: ['costs', 'menu', 'margins'],
    modules: 5,
    sponsored: false,
    lessons: [
      'Understanding your true food cost percentage',
      'Menu engineering: identifying star vs. dog items',
      'Portion control and yield management',
      'Seasonal ingredient substitution strategies',
      'Tracking and reducing plate waste',
    ],
  },
  {
    slug: 'team-retention',
    title: 'Team Retention Playbook',
    description: 'Cut staff turnover below 60% annually',
    duration: '60 min',
    level: 'intermediate',
    triggerMetric: 'staffTurnoverRate',
    triggerCondition: 'above_peer_avg',
    tags: ['hiring', 'culture', 'retention'],
    modules: 6,
    lessons: [
      'Why restaurant staff leave (and how to fix it)',
      'Building an onboarding process that sticks',
      'Recognition and non-monetary incentives',
      'Scheduling fairness and work-life balance',
      'Creating a feedback culture',
      'Exit interview patterns and action plans',
    ],
  },
  {
    slug: 'pricing-strategy',
    title: 'Pricing Strategy for Restaurants',
    description: 'Stop over-discounting, boost avg order value',
    duration: '30 min',
    level: 'beginner',
    triggerMetric: 'avgOrderValue',
    triggerCondition: 'below_peer_avg',
    tags: ['pricing', 'revenue'],
    modules: 4,
    lessons: [
      'Psychological pricing principles for menus',
      'Upselling and cross-selling without pressure',
      'When discounts help vs. hurt your brand',
      'Testing price changes with A/B thinking',
    ],
  },
  {
    slug: 'kitchen-operations',
    title: 'Kitchen Operations Efficiency',
    description: 'Reduce ticket times and kitchen waste',
    duration: '50 min',
    level: 'advanced',
    triggerMetric: 'kitchenLatency',
    triggerCondition: 'above_peer_avg',
    tags: ['operations', 'waste', 'speed'],
    modules: 7,
    lessons: [
      'Station design for peak throughput',
      'Mise en place discipline and prep scheduling',
      'Line communication and ticket management',
      'Reducing re-fires and quality mistakes',
      'Waste audit: tracking and eliminating top 5 waste sources',
      'Managing kitchen staff during rush',
      'KPI dashboards for kitchen managers',
    ],
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing for Restaurants',
    description: 'Grow repeat customers with low-cost digital campaigns',
    duration: '40 min',
    level: 'beginner',
    triggerMetric: 'repeatCustomerRate',
    triggerCondition: 'below_peer_avg',
    tags: ['marketing', 'loyalty', 'growth'],
    modules: 5,
    lessons: [
      'Setting up Google Business Profile correctly',
      'Instagram content that drives reservations',
      'WhatsApp and SMS for loyalty programs',
      'Running low-budget targeted ads',
      'Turning reviews into repeat visits',
    ],
  },
  {
    slug: 'supplier-negotiation',
    title: 'Supplier Negotiation Masterclass',
    description: 'Get better prices and payment terms from suppliers',
    duration: '35 min',
    level: 'intermediate',
    triggerMetric: 'supplierCostPct',
    triggerCondition: 'above_peer_avg',
    tags: ['procurement', 'costs'],
    modules: 4,
    lessons: [
      'Mapping your supplier dependency and leverage points',
      'Negotiation scripts for common scenarios',
      'Volume consolidation and co-op buying',
      'Contract terms that protect your cash flow',
    ],
  },
  // General courses — always visible regardless of operational data
  {
    slug: 'restaurant-finance-basics',
    title: 'Restaurant Finance Fundamentals',
    description: 'Master P&L, cash flow, and break-even for restaurant owners',
    duration: '55 min',
    level: 'beginner',
    tags: ['finance', 'operations', 'margins'],
    modules: 6,
    lessons: [
      'Reading your P&L like a pro',
      'Break-even analysis for menu and staffing decisions',
      'Cash flow management through slow seasons',
      'Prime cost: the number that runs your restaurant',
      'Depreciation, CAPEX, and equipment decisions',
      'Tax-ready bookkeeping habits',
    ],
  },
  {
    slug: 'health-safety-compliance',
    title: 'Health & Safety Compliance',
    description: 'Stay inspection-ready and protect your licence',
    duration: '40 min',
    level: 'beginner',
    tags: ['compliance', 'operations'],
    modules: 5,
    lessons: [
      'FSSAI requirements for Indian restaurants',
      'Temperature logs and cold-chain management',
      'Pest control documentation',
      'Staff health certificates and records',
      'Surviving a surprise health inspection',
    ],
  },
  {
    slug: 'online-ordering-setup',
    title: 'Online Ordering & Delivery Optimisation',
    description: 'Maximise ratings and margins on Swiggy, Zomato, and direct channels',
    duration: '35 min',
    level: 'beginner',
    tags: ['growth', 'marketing', 'operations'],
    modules: 4,
    lessons: [
      'Photography and copywriting for delivery platforms',
      'Setting delivery zones and surge pricing',
      'Packaging for quality preservation',
      'Managing bad reviews and platform disputes',
    ],
  },
  {
    slug: 'leadership-fundamentals',
    title: 'Restaurant Leadership Fundamentals',
    description: 'Lead your team with clarity, confidence, and consistency',
    duration: '45 min',
    level: 'intermediate',
    tags: ['hiring', 'culture', 'operations'],
    modules: 5,
    lessons: [
      'Shift briefings that actually land',
      'Giving feedback in a high-pressure kitchen',
      'Delegation without losing control',
      'Managing conflict between front-of-house and back-of-house',
      'Building your management team from within',
    ],
  },
];

export function getCatalogBySlug(slug: string): TrainingModule | undefined {
  return TRAINING_CATALOG.find((c) => c.slug === slug);
}

export function getGeneralCourses(): TrainingModule[] {
  return TRAINING_CATALOG.filter((c) => !c.triggerMetric);
}
