// Comprehensive Mock Data for RestoPapa Application
// This file contains extensive mock data for all features

export const mockData = {
  // Users with proper authentication data
  users: [
    // Admins
    {
      id: 'mock-admin-1',
      email: 'admin@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$znHIcmZ7b20WlnEEnZDKyA$EqSxJWXwFBlH9ZnqfCrEU71gTiG81vX8TJPGruzlMao', // Password: Password123
      phone: '+1234567890',
      role: 'ADMIN',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-admin-2',
      email: 'admin2@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567800',
      role: 'ADMIN',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Restaurant Owners
    {
      id: 'mock-restaurant-1',
      email: 'restaurant@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$znHIcmZ7b20WlnEEnZDKyA$EqSxJWXwFBlH9ZnqfCrEU71gTiG81vX8TJPGruzlMao', // Password: Password123
      phone: '+1234567891',
      role: 'RESTAURANT',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-2',
      email: 'restaurant2@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567801',
      role: 'RESTAURANT',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-3',
      email: 'restaurant3@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567802',
      role: 'RESTAURANT',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Vendors
    {
      id: 'mock-vendor-1',
      email: 'vendor@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$znHIcmZ7b20WlnEEnZDKyA$EqSxJWXwFBlH9ZnqfCrEU71gTiG81vX8TJPGruzlMao', // Password: Password123
      phone: '+1234567892',
      role: 'VENDOR',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-vendor-2',
      email: 'vendor2@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567803',
      role: 'VENDOR',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-vendor-3',
      email: 'vendor3@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567804',
      role: 'VENDOR',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Employees
    {
      id: 'mock-employee-1',
      email: 'employee@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$znHIcmZ7b20WlnEEnZDKyA$EqSxJWXwFBlH9ZnqfCrEU71gTiG81vX8TJPGruzlMao', // Password: Password123
      phone: '+1234567893',
      role: 'EMPLOYEE',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-employee-2',
      email: 'employee2@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567805',
      role: 'EMPLOYEE',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-employee-3',
      email: 'employee3@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567806',
      role: 'EMPLOYEE',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-employee-4',
      email: 'employee4@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567807',
      role: 'EMPLOYEE',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Customers
    {
      id: 'mock-customer-1',
      email: 'customer@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$znHIcmZ7b20WlnEEnZDKyA$EqSxJWXwFBlH9ZnqfCrEU71gTiG81vX8TJPGruzlMao', // Password: Password123
      phone: '+1234567894',
      role: 'CUSTOMER',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-customer-2',
      email: 'customer2@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567808',
      role: 'CUSTOMER',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-customer-3',
      email: 'customer3@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567809',
      role: 'CUSTOMER',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-customer-4',
      email: 'customer4@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567810',
      role: 'CUSTOMER',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-customer-5',
      email: 'customer5@restopapa.com',
      passwordHash: '$argon2id$v=19$m=65536,t=3,p=4$wbSoSWLB6mCuhAbTBD8pWQ$s6pR2pF0uGKJzbYMksYSV+D4lHMyuHo+PRFwNsHEbv0',
      phone: '+1234567811',
      role: 'CUSTOMER',
      isActive: true,
      emailVerifiedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // User profiles
  profiles: [
    // Admin profiles
    {
      id: 'mock-profile-admin-1',
      userId: 'mock-admin-1',
      firstName: 'System',
      lastName: 'Administrator',
      bio: 'Platform Administrator managing the RestoPapa ecosystem',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '400001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-admin-2',
      userId: 'mock-admin-2',
      firstName: 'Sarah',
      lastName: 'Johnson',
      bio: 'Community Manager and Customer Support Lead',
      avatar: 'https://images.unsplash.com/photo-1494790108755-2616c7b5c5d3?w=150&h=150&fit=crop&crop=face',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      zipCode: '110001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Restaurant Owner profiles
    {
      id: 'mock-profile-restaurant-1',
      userId: 'mock-restaurant-1',
      firstName: 'Rahul',
      lastName: 'Sharma',
      bio: 'Passionate restaurant owner dedicated to serving great food',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra', 
      country: 'India',
      zipCode: '400001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-restaurant-2',
      userId: 'mock-restaurant-2',
      firstName: 'Priya',
      lastName: 'Mehta',
      bio: 'Third-generation restaurant owner specializing in authentic Indian cuisine',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      zipCode: '560001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-restaurant-3',
      userId: 'mock-restaurant-3',
      firstName: 'Vikram',
      lastName: 'Singh',
      bio: 'Chef-turned-owner focusing on fusion cuisine and modern dining experiences',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '411001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Vendor profiles
    {
      id: 'mock-profile-vendor-1',
      userId: 'mock-vendor-1',
      firstName: 'Amit',
      lastName: 'Patel',
      bio: 'Supplier of premium ingredients and restaurant supplies',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India', 
      zipCode: '400002',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-vendor-2',
      userId: 'mock-vendor-2',
      firstName: 'Sunita',
      lastName: 'Kumar',
      bio: 'Organic farm owner supplying fresh produce to restaurants across the city',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      zipCode: '600001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-vendor-3',
      userId: 'mock-vendor-3',
      firstName: 'Rajesh',
      lastName: 'Gupta',
      bio: 'Equipment supplier and maintenance expert for commercial kitchens',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
      zipCode: '500001',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Employee profiles
    {
      id: 'mock-profile-employee-1',
      userId: 'mock-employee-1',
      firstName: 'Arjun',
      lastName: 'Reddy',
      bio: 'Experienced chef with 5+ years in the industry',
      avatar: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '400003',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-employee-2',
      userId: 'mock-employee-2',
      firstName: 'Meera',
      lastName: 'Joshi',
      bio: 'Sous chef passionate about creating innovative dishes',
      avatar: 'https://images.unsplash.com/photo-1494790108755-2616c7b5c5d3?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '400050',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-employee-3',
      userId: 'mock-employee-3',
      firstName: 'Karan',
      lastName: 'Verma',
      bio: 'Restaurant server with excellent customer service skills',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '411002',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-employee-4',
      userId: 'mock-employee-4',
      firstName: 'Deepika',
      lastName: 'Nair',
      bio: 'Assistant manager specializing in restaurant operations',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      zipCode: '560002',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Customer profiles
    {
      id: 'mock-profile-customer-1',
      userId: 'mock-customer-1',
      firstName: 'Aditi',
      lastName: 'Chopra',
      bio: 'Food enthusiast and regular customer',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '400004',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-customer-2',
      userId: 'mock-customer-2',
      firstName: 'Rohan',
      lastName: 'Agarwal',
      bio: 'Corporate professional who loves exploring new restaurants',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
      zipCode: '110002',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-customer-3',
      userId: 'mock-customer-3',
      firstName: 'Kavya',
      lastName: 'Iyer',
      bio: 'Food blogger and social media influencer',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      zipCode: '560003',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-customer-4',
      userId: 'mock-customer-4',
      firstName: 'Nikhil',
      lastName: 'Desai',
      bio: 'Tech entrepreneur and food lover',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      zipCode: '411003',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-profile-customer-5',
      userId: 'mock-customer-5',
      firstName: 'Anjali',
      lastName: 'Malhotra',
      bio: 'Family person who enjoys dining out on weekends',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      zipCode: '600002',
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Comprehensive restaurant data
  restaurants: [
    {
      id: 'mock-restaurant-data-1',
      userId: 'mock-restaurant-1',
      name: 'Best Burgers',
      description: 'Authentic burgers and fast food with premium ingredients',
      cuisineType: ['American', 'Fast Food'],
      businessAddress: '123 Food Street, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400001',
      businessPhone: '+919876543210',
      businessEmail: 'contact@bestburgers.com',
      registrationNumber: 'REG123456',
      gstNumber: 'GST123456789',
      fssaiNumber: 'FSSAI123456',
      panNumber: 'PAN123456',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.5,
      totalReviews: 125,
      isActive: true,
      operatingHours: {
        monday: { open: '10:00', close: '23:00', closed: false },
        tuesday: { open: '10:00', close: '23:00', closed: false },
        wednesday: { open: '10:00', close: '23:00', closed: false },
        thursday: { open: '10:00', close: '23:00', closed: false },
        friday: { open: '10:00', close: '00:00', closed: false },
        saturday: { open: '10:00', close: '00:00', closed: false },
        sunday: { open: '12:00', close: '22:00', closed: false }
      },
      amenities: ['WiFi', 'Air Conditioning', 'Parking', 'Online Ordering'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-data-2',
      userId: 'mock-restaurant-1',
      name: 'Spice Garden',
      description: 'Traditional Indian cuisine with authentic flavors',
      cuisineType: ['Indian', 'Vegetarian', 'North Indian'],
      businessAddress: '456 Spice Lane, Juhu',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400049',
      businessPhone: '+919876543211',
      businessEmail: 'contact@spicegarden.com',
      registrationNumber: 'REG123457',
      gstNumber: 'GST123456790',
      fssaiNumber: 'FSSAI123457',
      panNumber: 'PAN123457',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.8,
      totalReviews: 89,
      isActive: true,
      operatingHours: {
        monday: { open: '11:00', close: '22:30', closed: false },
        tuesday: { open: '11:00', close: '22:30', closed: false },
        wednesday: { open: '11:00', close: '22:30', closed: false },
        thursday: { open: '11:00', close: '22:30', closed: false },
        friday: { open: '11:00', close: '23:00', closed: false },
        saturday: { open: '11:00', close: '23:00', closed: false },
        sunday: { open: '11:00', close: '22:30', closed: false }
      },
      amenities: ['WiFi', 'Air Conditioning', 'Valet Parking', 'Family Seating'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-data-3',
      userId: 'mock-restaurant-2',
      name: 'Flavors of Karnataka',
      description: 'Authentic South Indian dishes served in a traditional setting',
      cuisineType: ['South Indian', 'Vegetarian', 'Udupi'],
      businessAddress: '789 Heritage Street, Koramangala',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560034',
      businessPhone: '+919876543212',
      businessEmail: 'contact@flavorskarnataka.com',
      registrationNumber: 'REG123458',
      gstNumber: 'GST123456791',
      fssaiNumber: 'FSSAI123458',
      panNumber: 'PAN123458',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.6,
      totalReviews: 156,
      isActive: true,
      operatingHours: {
        monday: { open: '08:00', close: '22:00', closed: false },
        tuesday: { open: '08:00', close: '22:00', closed: false },
        wednesday: { open: '08:00', close: '22:00', closed: false },
        thursday: { open: '08:00', close: '22:00', closed: false },
        friday: { open: '08:00', close: '22:00', closed: false },
        saturday: { open: '08:00', close: '22:00', closed: false },
        sunday: { open: '08:00', close: '22:00', closed: false }
      },
      amenities: ['WiFi', 'Air Conditioning', 'Parking', 'Traditional Seating'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-data-4',
      userId: 'mock-restaurant-2',
      name: 'Urban Bites',
      description: 'Modern fusion cuisine with a contemporary twist',
      cuisineType: ['Continental', 'Fusion', 'Italian'],
      businessAddress: '321 Modern Plaza, Indiranagar',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560038',
      businessPhone: '+919876543213',
      businessEmail: 'contact@urbanbites.com',
      registrationNumber: 'REG123459',
      gstNumber: 'GST123456792',
      fssaiNumber: 'FSSAI123459',
      panNumber: 'PAN123459',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.7,
      totalReviews: 98,
      isActive: true,
      operatingHours: {
        monday: { open: '12:00', close: '23:00', closed: false },
        tuesday: { open: '12:00', close: '23:00', closed: false },
        wednesday: { open: '12:00', close: '23:00', closed: false },
        thursday: { open: '12:00', close: '23:00', closed: false },
        friday: { open: '12:00', close: '00:00', closed: false },
        saturday: { open: '12:00', close: '00:00', closed: false },
        sunday: { open: '12:00', close: '23:00', closed: false }
      },
      amenities: ['WiFi', 'Air Conditioning', 'Valet Parking', 'Live Music', 'Bar'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-data-5',
      userId: 'mock-restaurant-3',
      name: 'Maharashtrian Tadka',
      description: 'Traditional Maharashtrian cuisine with homestyle cooking',
      cuisineType: ['Maharashtrian', 'Traditional', 'Vegetarian'],
      businessAddress: '654 Cultural Avenue, Shivajinagar',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411005',
      businessPhone: '+919876543214',
      businessEmail: 'contact@maharashtrian-tadka.com',
      registrationNumber: 'REG123460',
      gstNumber: 'GST123456793',
      fssaiNumber: 'FSSAI123460',
      panNumber: 'PAN123460',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.4,
      totalReviews: 78,
      isActive: true,
      operatingHours: {
        monday: { open: '11:00', close: '15:00', closed: false },
        tuesday: { open: '11:00', close: '15:00', closed: false },
        wednesday: { open: '11:00', close: '15:00', closed: false },
        thursday: { open: '11:00', close: '15:00', closed: false },
        friday: { open: '11:00', close: '15:00', closed: false },
        saturday: { open: '11:00', close: '15:00', closed: false },
        sunday: { open: '11:00', close: '15:00', closed: true }
      },
      amenities: ['Air Conditioning', 'Family Seating', 'Traditional Ambience'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-restaurant-data-6',
      userId: 'mock-restaurant-3',
      name: 'Fusion Delight',
      description: 'Indo-Chinese fusion with innovative flavors',
      cuisineType: ['Indo-Chinese', 'Fusion', 'Asian'],
      businessAddress: '987 Fusion Street, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411001',
      businessPhone: '+919876543215',
      businessEmail: 'contact@fusiondelight.com',
      registrationNumber: 'REG123461',
      gstNumber: 'GST123456794',
      fssaiNumber: 'FSSAI123461',
      panNumber: 'PAN123461',
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.3,
      totalReviews: 67,
      isActive: true,
      operatingHours: {
        monday: { open: '18:00', close: '23:30', closed: false },
        tuesday: { open: '18:00', close: '23:30', closed: false },
        wednesday: { open: '18:00', close: '23:30', closed: false },
        thursday: { open: '18:00', close: '23:30', closed: false },
        friday: { open: '18:00', close: '00:30', closed: false },
        saturday: { open: '18:00', close: '00:30', closed: false },
        sunday: { open: '18:00', close: '23:30', closed: false }
      },
      amenities: ['WiFi', 'Air Conditioning', 'Parking', 'Takeaway', 'Home Delivery'],
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Comprehensive vendor data
  vendors: [
    {
      id: 'mock-vendor-data-1',
      userId: 'mock-vendor-1',
      businessName: 'Fresh Supplies Co',
      businessType: 'Food Distributor',
      businessAddress: '789 Supply Street, Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400002',
      businessPhone: '+919876543210',
      businessEmail: 'contact@freshsupplies.com',
      description: 'Premium food ingredients and restaurant supplies',
      categories: ['Vegetables', 'Spices', 'Dairy', 'Meat', 'Kitchen Equipment'],
      minOrderValue: 500,
      deliveryAreas: ['Mumbai', 'Navi Mumbai', 'Thane'],
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.7,
      totalReviews: 67,
      isActive: true,
      operatingHours: {
        monday: { open: '06:00', close: '20:00', closed: false },
        tuesday: { open: '06:00', close: '20:00', closed: false },
        wednesday: { open: '06:00', close: '20:00', closed: false },
        thursday: { open: '06:00', close: '20:00', closed: false },
        friday: { open: '06:00', close: '20:00', closed: false },
        saturday: { open: '06:00', close: '18:00', closed: false },
        sunday: { open: '08:00', close: '16:00', closed: false }
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'mock-vendor-data-2',
      userId: 'mock-vendor-1',
      businessName: 'Kitchen Pro Equipment',
      businessType: 'Equipment Supplier',
      businessAddress: '321 Equipment Plaza, Worli',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400025',
      businessPhone: '+919876543212',
      businessEmail: 'contact@kitchenpro.com',
      description: 'Commercial kitchen equipment and maintenance services',
      categories: ['Kitchen Equipment', 'Maintenance', 'Installation'],
      minOrderValue: 2000,
      deliveryAreas: ['Mumbai', 'Pune', 'Nashik'],
      verificationStatus: 'VERIFIED',
      verifiedAt: new Date(),
      rating: 4.6,
      totalReviews: 34,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Comprehensive marketplace products
  products: [
    // Fresh Vegetables - Vendor 1
    {
      id: 'prod-001',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-vegetables',
      name: 'Premium Tomatoes',
      description: 'Fresh, organic tomatoes perfect for cooking',
      price: 45.00,
      unit: 'kg',
      minOrderQuantity: 2,
      maxOrderQuantity: 50,
      isAvailable: true,
      stockQuantity: 200,
      images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop'],
      nutritionalInfo: {
        calories: 18,
        protein: 0.9,
        carbs: 3.9,
        fat: 0.2,
        fiber: 1.2
      },
      tags: ['organic', 'fresh', 'local'],
      rating: 4.8,
      totalReviews: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-002',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-vegetables',
      name: 'Fresh Onions',
      description: 'High-quality red onions, essential for every kitchen',
      price: 35.00,
      unit: 'kg',
      minOrderQuantity: 5,
      maxOrderQuantity: 100,
      isAvailable: true,
      stockQuantity: 500,
      images: ['https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=400&h=300&fit=crop'],
      tags: ['fresh', 'local'],
      rating: 4.5,
      totalReviews: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-003',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-vegetables',
      name: 'Organic Potatoes',
      description: 'Farm-fresh organic potatoes, perfect for all cooking needs',
      price: 28.00,
      unit: 'kg',
      minOrderQuantity: 10,
      maxOrderQuantity: 100,
      isAvailable: true,
      stockQuantity: 300,
      images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop'],
      tags: ['organic', 'fresh', 'versatile'],
      rating: 4.6,
      totalReviews: 31,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-004',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-vegetables',
      name: 'Green Bell Peppers',
      description: 'Crisp and fresh green bell peppers for cooking and salads',
      price: 55.00,
      unit: 'kg',
      minOrderQuantity: 2,
      maxOrderQuantity: 20,
      isAvailable: true,
      stockQuantity: 80,
      images: ['https://images.unsplash.com/photo-1563203369-e5966985e9ce?w=400&h=300&fit=crop'],
      tags: ['fresh', 'crisp', 'colorful'],
      rating: 4.4,
      totalReviews: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-005',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-vegetables',
      name: 'Fresh Carrots',
      description: 'Sweet and crunchy carrots, great for cooking and garnishing',
      price: 42.00,
      unit: 'kg',
      minOrderQuantity: 3,
      maxOrderQuantity: 30,
      isAvailable: true,
      stockQuantity: 120,
      images: ['https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=300&fit=crop'],
      tags: ['sweet', 'crunchy', 'nutritious'],
      rating: 4.7,
      totalReviews: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    
    // Spices & Seasonings - Multiple vendors
    {
      id: 'prod-006',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-spices',
      name: 'Garam Masala Powder',
      description: 'Authentic blend of Indian spices, ground fresh',
      price: 280.00,
      unit: 'kg',
      minOrderQuantity: 1,
      maxOrderQuantity: 10,
      isAvailable: true,
      stockQuantity: 25,
      images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop'],
      tags: ['spices', 'authentic', 'ground fresh'],
      rating: 4.9,
      totalReviews: 45,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-007',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-spices',
      name: 'Turmeric Powder',
      description: 'Pure organic turmeric powder with anti-inflammatory properties',
      price: 180.00,
      unit: 'kg',
      minOrderQuantity: 1,
      maxOrderQuantity: 15,
      isAvailable: true,
      stockQuantity: 35,
      images: ['https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop'],
      tags: ['organic', 'medicinal', 'pure'],
      rating: 4.8,
      totalReviews: 38,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-008',
      vendorId: 'mock-vendor-data-3',
      categoryId: 'cat-spices',
      name: 'Cumin Seeds',
      description: 'Premium quality cumin seeds for tempering and flavor',
      price: 320.00,
      unit: 'kg',
      minOrderQuantity: 1,
      maxOrderQuantity: 8,
      isAvailable: true,
      stockQuantity: 18,
      images: ['https://images.unsplash.com/photo-1599917846506-2da53e1c08de?w=400&h=300&fit=crop'],
      tags: ['premium', 'aromatic', 'tempering'],
      rating: 4.7,
      totalReviews: 28,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-009',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-spices',
      name: 'Red Chili Powder',
      description: 'Fiery red chili powder for heat and color in dishes',
      price: 250.00,
      unit: 'kg',
      minOrderQuantity: 1,
      maxOrderQuantity: 12,
      isAvailable: true,
      stockQuantity: 30,
      images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop'],
      tags: ['spicy', 'vibrant', 'essential'],
      rating: 4.6,
      totalReviews: 33,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    
    // Kitchen Equipment - Vendor 2 specializes in equipment
    {
      id: 'prod-010',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-equipment',
      name: 'Commercial Gas Burner',
      description: 'Heavy-duty 4-burner commercial gas stove',
      price: 25000.00,
      unit: 'piece',
      minOrderQuantity: 1,
      maxOrderQuantity: 5,
      isAvailable: true,
      stockQuantity: 8,
      images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop'],
      specifications: {
        burners: 4,
        material: 'Stainless Steel',
        dimensions: '120x60x85 cm',
        warranty: '2 years'
      },
      tags: ['commercial', 'heavy-duty', 'stainless steel'],
      rating: 4.7,
      totalReviews: 12,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-011',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-equipment',
      name: 'Commercial Deep Fryer',
      description: 'Electric deep fryer for commercial kitchen use',
      price: 18500.00,
      unit: 'piece',
      minOrderQuantity: 1,
      maxOrderQuantity: 3,
      isAvailable: true,
      stockQuantity: 5,
      images: ['https://images.unsplash.com/photo-1556909114-6b2d6f73a7d6?w=400&h=300&fit=crop'],
      specifications: {
        capacity: '20L',
        material: 'Stainless Steel',
        power: '3000W',
        warranty: '1 year'
      },
      tags: ['commercial', 'electric', 'high-capacity'],
      rating: 4.5,
      totalReviews: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-012',
      vendorId: 'mock-vendor-data-3',
      categoryId: 'cat-equipment',
      name: 'Professional Chef Knives Set',
      description: 'Complete set of 8 professional chef knives with storage block',
      price: 4500.00,
      unit: 'set',
      minOrderQuantity: 1,
      maxOrderQuantity: 10,
      isAvailable: true,
      stockQuantity: 15,
      images: ['https://images.unsplash.com/photo-1544160315-6fbbec137309?w=400&h=300&fit=crop'],
      specifications: {
        pieces: 8,
        material: 'High Carbon Steel',
        includes: 'Storage Block',
        warranty: '5 years'
      },
      tags: ['professional', 'sharp', 'durable'],
      rating: 4.9,
      totalReviews: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-013',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-equipment',
      name: 'Commercial Mixer Grinder',
      description: 'Heavy-duty mixer grinder for commercial kitchen grinding needs',
      price: 12000.00,
      unit: 'piece',
      minOrderQuantity: 1,
      maxOrderQuantity: 5,
      isAvailable: true,
      stockQuantity: 12,
      images: ['https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&h=300&fit=crop'],
      specifications: {
        power: '1500W',
        jars: '3 stainless steel jars',
        capacity: '2L each',
        warranty: '2 years'
      },
      tags: ['commercial', 'powerful', 'versatile'],
      rating: 4.6,
      totalReviews: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    
    // Dairy Products
    {
      id: 'prod-014',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-dairy',
      name: 'Fresh Whole Milk',
      description: 'Farm-fresh whole milk, rich in nutrients and flavor',
      price: 55.00,
      unit: 'liter',
      minOrderQuantity: 10,
      maxOrderQuantity: 100,
      isAvailable: true,
      stockQuantity: 200,
      images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=300&fit=crop'],
      nutritionalInfo: {
        fat: 3.5,
        protein: 3.2,
        calcium: '120mg per 100ml'
      },
      tags: ['fresh', 'farm', 'nutritious'],
      rating: 4.7,
      totalReviews: 42,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-015',
      vendorId: 'mock-vendor-data-2',
      categoryId: 'cat-dairy',
      name: 'Paneer (Cottage Cheese)',
      description: 'Fresh homemade paneer, perfect for Indian cooking',
      price: 280.00,
      unit: 'kg',
      minOrderQuantity: 1,
      maxOrderQuantity: 20,
      isAvailable: true,
      stockQuantity: 50,
      images: ['https://images.unsplash.com/photo-1631788140049-7b5b4f73be9b?w=400&h=300&fit=crop'],
      tags: ['fresh', 'homemade', 'protein-rich'],
      rating: 4.8,
      totalReviews: 35,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-016',
      vendorId: 'mock-vendor-data-1',
      categoryId: 'cat-dairy',
      name: 'Greek Yogurt',
      description: 'Thick and creamy Greek yogurt, high in protein',
      price: 120.00,
      unit: 'kg',
      minOrderQuantity: 2,
      maxOrderQuantity: 25,
      isAvailable: true,
      stockQuantity: 80,
      images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop'],
      nutritionalInfo: {
        protein: '10g per 100g',
        probiotics: 'Live cultures',
        fat: 'Low fat'
      },
      tags: ['thick', 'creamy', 'high-protein'],
      rating: 4.6,
      totalReviews: 28,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    
    // More Vegetables from different vendors
    {
      id: 'prod-017',
      vendorId: 'mock-vendor-data-3',
      categoryId: 'cat-vegetables',
      name: 'Fresh Spinach',
      description: 'Tender fresh spinach leaves, rich in iron and vitamins',
      price: 65.00,
      unit: 'kg',
      minOrderQuantity: 2,
      maxOrderQuantity: 15,
      isAvailable: true,
      stockQuantity: 40,
      images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop'],
      nutritionalInfo: {
        iron: 'High',
        vitamins: 'A, C, K',
        calories: '23 per 100g'
      },
      tags: ['leafy', 'nutritious', 'fresh'],
      rating: 4.5,
      totalReviews: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'prod-018',
      vendorId: 'mock-vendor-data-3',
      categoryId: 'cat-vegetables',
      name: 'Cauliflower',
      description: 'Fresh white cauliflower heads, perfect for curries',
      price: 38.00,
      unit: 'kg',
      minOrderQuantity: 3,
      maxOrderQuantity: 25,
      isAvailable: true,
      stockQuantity: 60,
      images: ['https://images.unsplash.com/photo-1568584711271-2b34ff59ba59?w=400&h=300&fit=crop'],
      tags: ['fresh', 'white', 'versatile'],
      rating: 4.4,
      totalReviews: 26,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Product categories
  categories: [
    {
      id: 'cat-vegetables',
      name: 'Fresh Vegetables',
      slug: 'vegetables',
      description: 'Farm-fresh vegetables and produce',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=300&h=200&fit=crop',
      parentId: null,
      isActive: true,
      sortOrder: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cat-spices',
      name: 'Spices & Seasonings',
      slug: 'spices',
      description: 'Authentic spices and seasonings',
      image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=300&h=200&fit=crop',
      parentId: null,
      isActive: true,
      sortOrder: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cat-equipment',
      name: 'Kitchen Equipment',
      slug: 'equipment',
      description: 'Commercial kitchen equipment and tools',
      image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=200&fit=crop',
      parentId: null,
      isActive: true,
      sortOrder: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cat-dairy',
      name: 'Dairy Products',
      slug: 'dairy',
      description: 'Fresh dairy products and alternatives',
      image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300&h=200&fit=crop',
      parentId: null,
      isActive: true,
      sortOrder: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Sample orders
  orders: [
    // Restaurant Orders
    {
      id: 'order-001',
      orderNumber: 'ORD-20240313-001',
      customerId: 'mock-customer-1',
      restaurantId: 'mock-restaurant-data-1',
      vendorId: null,
      type: 'DINE_IN',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'CARD',
      items: [
        {
          id: 'item-1',
          name: 'Classic Burger',
          quantity: 2,
          price: 350,
          total: 700,
          specifications: 'Medium rare, no onions'
        },
        {
          id: 'item-2',
          name: 'French Fries',
          quantity: 1,
          price: 150,
          total: 150
        },
        {
          id: 'item-3',
          name: 'Coca Cola',
          quantity: 2,
          price: 50,
          total: 100
        }
      ],
      subtotal: 950,
      taxes: 114,
      deliveryFee: 0,
      total: 1064,
      tableNumber: 'T-05',
      specialInstructions: 'Extra crispy fries',
      customerNotes: 'Anniversary dinner',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
      completedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
    {
      id: 'order-002',
      orderNumber: 'ORD-20240313-002',
      customerId: 'mock-customer-2',
      restaurantId: 'mock-restaurant-data-2',
      vendorId: null,
      type: 'DELIVERY',
      status: 'PREPARING',
      paymentStatus: 'PAID',
      paymentMethod: 'UPI',
      items: [
        {
          id: 'item-4',
          name: 'Butter Chicken',
          quantity: 1,
          price: 420,
          total: 420
        },
        {
          id: 'item-5',
          name: 'Naan Bread',
          quantity: 3,
          price: 60,
          total: 180
        },
        {
          id: 'item-6',
          name: 'Basmati Rice',
          quantity: 1,
          price: 180,
          total: 180
        }
      ],
      subtotal: 780,
      taxes: 94,
      deliveryFee: 40,
      total: 914,
      deliveryAddress: {
        street: '456 Green Park',
        area: 'Koramangala',
        city: 'Bangalore',
        zipCode: '560034',
        phone: '+919876543216'
      },
      estimatedDelivery: new Date(Date.now() + 25 * 60 * 1000), // 25 minutes from now
      createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 minutes ago
      updatedAt: new Date(Date.now() - 2 * 60 * 1000), // 2 minutes ago
    },
    {
      id: 'order-003',
      orderNumber: 'ORD-20240313-003',
      customerId: 'mock-customer-3',
      restaurantId: 'mock-restaurant-data-3',
      vendorId: null,
      type: 'TAKEAWAY',
      status: 'READY',
      paymentStatus: 'PAID',
      paymentMethod: 'CASH',
      items: [
        {
          id: 'item-7',
          name: 'Masala Dosa',
          quantity: 2,
          price: 120,
          total: 240
        },
        {
          id: 'item-8',
          name: 'Filter Coffee',
          quantity: 2,
          price: 35,
          total: 70
        },
        {
          id: 'item-9',
          name: 'Sambar Vada',
          quantity: 1,
          price: 80,
          total: 80
        }
      ],
      subtotal: 390,
      taxes: 47,
      deliveryFee: 0,
      total: 437,
      specialInstructions: 'Extra sambar on the side',
      pickupTime: new Date(Date.now() + 10 * 60 * 1000), // 10 minutes from now
      createdAt: new Date(Date.now() - 20 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 60 * 1000),
    },
    
    // Vendor/Marketplace Orders
    {
      id: 'order-004',
      orderNumber: 'ORD-20240313-004',
      customerId: 'mock-customer-1',
      restaurantId: null,
      vendorId: 'mock-vendor-data-1',
      type: 'DELIVERY',
      status: 'IN_PROGRESS',
      paymentStatus: 'PAID',
      paymentMethod: 'UPI',
      items: [
        {
          id: 'item-10',
          name: 'Premium Tomatoes',
          quantity: 5,
          price: 45,
          total: 225
        },
        {
          id: 'item-11',
          name: 'Fresh Onions',
          quantity: 10,
          price: 35,
          total: 350
        },
        {
          id: 'item-12',
          name: 'Garam Masala Powder',
          quantity: 2,
          price: 280,
          total: 560
        }
      ],
      subtotal: 1135,
      taxes: 136,
      deliveryFee: 60,
      total: 1331,
      deliveryAddress: {
        street: '123 Restaurant Street',
        area: 'Bandra West',
        city: 'Mumbai',
        zipCode: '400050',
        phone: '+919876543215'
      },
      estimatedDelivery: new Date(Date.now() + 45 * 60 * 1000), // 45 minutes from now
      createdAt: new Date(Date.now() - 30 * 60 * 1000), // 30 minutes ago
      updatedAt: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
    },
    {
      id: 'order-005',
      orderNumber: 'ORD-20240313-005',
      customerId: 'mock-customer-4',
      restaurantId: null,
      vendorId: 'mock-vendor-data-2',
      type: 'PICKUP',
      status: 'COMPLETED',
      paymentStatus: 'PAID',
      paymentMethod: 'CARD',
      items: [
        {
          id: 'item-13',
          name: 'Commercial Gas Burner',
          quantity: 1,
          price: 25000,
          total: 25000
        }
      ],
      subtotal: 25000,
      taxes: 4500,
      deliveryFee: 0,
      total: 29500,
      specialInstructions: 'Installation service required',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'order-006',
      orderNumber: 'ORD-20240313-006',
      customerId: 'mock-customer-5',
      restaurantId: 'mock-restaurant-data-4',
      vendorId: null,
      type: 'DINE_IN',
      status: 'CANCELLED',
      paymentStatus: 'REFUNDED',
      paymentMethod: 'CARD',
      items: [
        {
          id: 'item-14',
          name: 'Pasta Carbonara',
          quantity: 2,
          price: 450,
          total: 900
        },
        {
          id: 'item-15',
          name: 'Garlic Bread',
          quantity: 1,
          price: 180,
          total: 180
        }
      ],
      subtotal: 1080,
      taxes: 130,
      deliveryFee: 0,
      total: 1210,
      tableNumber: 'T-12',
      cancellationReason: 'Customer requested cancellation',
      refundAmount: 1210,
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      cancelledAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    }
  ],

  // Community posts and interactions
  posts: [
    {
      id: 'post-001',
      userId: 'mock-admin-1',
      title: 'Welcome to RestoPapa Community!',
      content: 'We are excited to launch this platform where restaurant owners, vendors, employees, and food enthusiasts can connect, share experiences, and grow together. Feel free to ask questions, share tips, and help each other succeed in the food industry.',
      tags: ['welcome', 'community', 'announcement'],
      category: 'ANNOUNCEMENT',
      isPublished: true,
      isPinned: true,
      viewCount: 145,
      likeCount: 23,
      commentCount: 8,
      shareCount: 5,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
      updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'post-002',
      userId: 'mock-restaurant-1',
      title: 'Looking for reliable vegetable suppliers in Mumbai',
      content: 'Hi everyone! We are expanding our restaurant operations and looking for dependable vegetable suppliers who can deliver fresh produce daily. We need tomatoes, onions, potatoes, and leafy greens. Quality is our top priority. Please reach out if you can help!',
      tags: ['suppliers', 'vegetables', 'mumbai', 'business'],
      category: 'BUSINESS_REQUEST',
      isPublished: true,
      isPinned: false,
      viewCount: 67,
      likeCount: 12,
      commentCount: 15,
      shareCount: 3,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'post-003',
      userId: 'mock-vendor-1',
      title: 'New Organic Spice Collection Available',
      content: 'Excited to announce our new range of organic spices sourced directly from farmers. We now have turmeric, cumin, coriander, and garam masala powder. All products are certified organic and ground fresh. Special launch discount of 20% for the first 50 orders!',
      tags: ['spices', 'organic', 'new products', 'discount'],
      category: 'PRODUCT_ANNOUNCEMENT',
      isPublished: true,
      isPinned: false,
      viewCount: 89,
      likeCount: 18,
      commentCount: 6,
      shareCount: 8,
      images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop'],
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'post-004',
      userId: 'mock-employee-1',
      title: 'Tips for Managing Kitchen Operations During Peak Hours',
      content: 'After 5+ years in restaurant kitchens, I\'ve learned some valuable lessons about managing operations during rush hours. Here are my top tips: 1) Prep everything possible beforehand 2) Establish clear communication channels 3) Train cross-functional skills 4) Implement a ticket priority system 5) Keep your workspace organized. Happy to answer any questions!',
      tags: ['kitchen', 'operations', 'tips', 'management'],
      category: 'TIPS_ADVICE',
      isPublished: true,
      isPinned: false,
      viewCount: 134,
      likeCount: 28,
      commentCount: 12,
      shareCount: 15,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'post-005',
      userId: 'mock-customer-3',
      title: 'Amazing Experience at Flavors of Karnataka!',
      content: 'Just had the most incredible South Indian meal at Flavors of Karnataka in Bangalore! The masala dosa was crispy and perfectly spiced, and their filter coffee was exactly like my grandmother used to make. The staff was incredibly friendly and the ambiance felt like home. Highly recommend this place to anyone looking for authentic Karnataka cuisine. 5 stars! 🌟',
      tags: ['review', 'south indian', 'bangalore', 'authentic'],
      category: 'REVIEW',
      isPublished: true,
      isPinned: false,
      viewCount: 78,
      likeCount: 22,
      commentCount: 8,
      shareCount: 6,
      images: ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop'],
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
      updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    },
    {
      id: 'post-006',
      userId: 'mock-restaurant-2',
      title: 'Celebrating 5 Years of Urban Bites!',
      content: 'Today marks 5 incredible years of Urban Bites! We started as a small fusion restaurant with a dream to bring innovative flavors to Bangalore. Thanks to our amazing customers, dedicated staff, and supportive vendor partners, we\'ve grown beyond our wildest dreams. To celebrate, we\'re offering 25% off all meals this weekend. Thank you for being part of our journey! 🎉',
      tags: ['anniversary', 'celebration', 'milestone', 'discount'],
      category: 'ANNOUNCEMENT',
      isPublished: true,
      isPinned: false,
      viewCount: 156,
      likeCount: 45,
      commentCount: 18,
      shareCount: 12,
      images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop'],
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
      updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
    {
      id: 'post-007',
      userId: 'mock-vendor-2',
      title: 'Food Safety Best Practices for Restaurant Owners',
      content: 'As a supplier to numerous restaurants, I see firsthand how important food safety is. Here are some crucial practices: 1) Maintain proper cold chain during delivery 2) Check supplier certifications regularly 3) Train staff on HACCP principles 4) Implement regular temperature monitoring 5) Keep detailed receiving logs. Food safety isn\'t just compliance - it\'s protecting your customers and reputation.',
      tags: ['food safety', 'best practices', 'compliance', 'training'],
      category: 'TIPS_ADVICE',
      isPublished: true,
      isPinned: false,
      viewCount: 92,
      likeCount: 31,
      commentCount: 14,
      shareCount: 22,
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
      updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    },
    {
      id: 'post-008',
      userId: 'mock-employee-2',
      title: 'Looking for Mentorship in Culinary Arts',
      content: 'Hi community! I\'m a sous chef with 3 years of experience, and I\'m passionate about advancing in culinary arts. I\'m particularly interested in modern Indian fusion cuisine and would love to connect with experienced chefs or restaurant owners who might be willing to mentor me. I\'m based in Mumbai but open to relocation for the right opportunity.',
      tags: ['mentorship', 'career', 'culinary', 'opportunity'],
      category: 'CAREER',
      isPublished: true,
      isPinned: false,
      viewCount: 68,
      likeCount: 16,
      commentCount: 9,
      shareCount: 4,
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
      updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    {
      id: 'post-009',
      userId: 'mock-vendor-3',
      title: 'New Commercial Kitchen Equipment Collection',
      content: 'Exciting news! We\'ve just received a shipment of state-of-the-art commercial kitchen equipment from Italy. Our collection now includes professional pizza ovens, pasta machines, high-capacity mixers, and precision induction cooktops. Perfect for restaurants looking to upgrade their kitchen efficiency. Offering installation support and 2-year warranty on all items.',
      tags: ['equipment', 'commercial', 'kitchen', 'italian'],
      category: 'PRODUCT_ANNOUNCEMENT',
      isPublished: true,
      isPinned: false,
      viewCount: 103,
      likeCount: 24,
      commentCount: 11,
      shareCount: 7,
      images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop'],
      createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000), // 18 hours ago
      updatedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    },
    {
      id: 'post-010',
      userId: 'mock-customer-4',
      title: 'Hosting a Corporate Event - Need Catering Recommendations',
      content: 'Our tech company is hosting a product launch event for 150 people next month in Pune. We\'re looking for catering services that can handle: 1) Mixed dietary requirements (veg/non-veg/vegan) 2) Professional presentation 3) On-time delivery 4) Reasonable pricing. The event is important for our company, so quality is crucial. Any recommendations from this community?',
      tags: ['catering', 'corporate', 'event', 'pune'],
      category: 'BUSINESS_REQUEST',
      isPublished: true,
      isPinned: false,
      viewCount: 84,
      likeCount: 19,
      commentCount: 25,
      shareCount: 8,
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
    {
      id: 'post-011',
      userId: 'mock-restaurant-3',
      title: 'Traditional Maharashtrian Thali - Recipe Heritage',
      content: 'Today I want to share the story behind our traditional Maharashtrian thali at our restaurant. Each component has deep cultural significance: the koshimbir represents freshness, bhakri symbolizes sustenance, and sol kadhi brings cooling balance. Our recipes have been passed down through three generations, and we take pride in preserving authentic flavors while adapting to modern tastes.',
      tags: ['traditional', 'maharashtrian', 'heritage', 'culture'],
      category: 'CULTURE_FOOD',
      isPublished: true,
      isPinned: false,
      viewCount: 127,
      likeCount: 38,
      commentCount: 16,
      shareCount: 20,
      images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop'],
      createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000), // 20 hours ago
      updatedAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
    }
  ],

  // Comments on posts
  comments: [
    {
      id: 'comment-001',
      postId: 'post-001',
      userId: 'mock-restaurant-1',
      content: 'Thank you for creating this platform! As a restaurant owner, I am excited about the opportunities this will bring.',
      parentId: null, // Top-level comment
      likeCount: 5,
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'comment-002',
      postId: 'post-002',
      userId: 'mock-vendor-1',
      content: 'We can definitely help with fresh vegetables! We deliver across Mumbai and have been supplying to restaurants for over 5 years. Let me send you our catalog.',
      parentId: null,
      likeCount: 8,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'comment-003',
      postId: 'post-002',
      userId: 'mock-restaurant-1',
      content: 'That sounds great! Please do send the catalog. I would also like to know about your delivery schedule and minimum order requirements.',
      parentId: 'comment-002', // Reply to comment-002
      likeCount: 2,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    }
  ],

  // Job postings
  jobs: [
    {
      id: 'job-001',
      restaurantId: 'mock-restaurant-data-1',
      title: 'Head Chef - Best Burgers',
      description: 'We are looking for an experienced head chef to lead our kitchen team at Best Burgers. The ideal candidate should have expertise in American cuisine and fast food preparation.',
      requirements: [
        '5+ years of experience as a chef',
        'Experience in fast food and American cuisine',
        'Leadership and team management skills',
        'Food safety certification required',
        'Ability to work in fast-paced environment'
      ],
      skills: ['Cooking', 'Kitchen Management', 'Team Leadership', 'Food Safety', 'Menu Planning'],
      jobType: 'FULL_TIME',
      experienceLevel: 'EXPERIENCED',
      salaryMin: 50000,
      salaryMax: 75000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Mumbai, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Health Insurance', 'Paid Time Off', 'Performance Bonus', 'Staff Meals'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
      applicationsCount: 12,
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'job-002',
      restaurantId: 'mock-restaurant-data-2',
      title: 'Restaurant Server - Spice Garden',
      description: 'Join our team as a restaurant server at Spice Garden. We are looking for friendly, professional individuals who are passionate about providing excellent customer service.',
      requirements: [
        '1+ years of experience in hospitality',
        'Excellent communication skills',
        'Customer service oriented',
        'Ability to work flexible hours',
        'Basic knowledge of Indian cuisine preferred'
      ],
      skills: ['Customer Service', 'Communication', 'Multitasking', 'POS Systems'],
      jobType: 'FULL_TIME',
      experienceLevel: 'ENTRY_LEVEL',
      salaryMin: 20000,
      salaryMax: 30000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Mumbai, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Staff Meals', 'Flexible Schedule', 'Tips'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
      applicationsCount: 8,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'job-003',
      restaurantId: 'mock-restaurant-data-3',
      title: 'Sous Chef - South Indian Cuisine',
      description: 'Flavors of Karnataka is seeking a passionate sous chef specializing in South Indian cuisine. Join our team to create authentic dishes that celebrate regional flavors.',
      requirements: [
        '3+ years of experience in South Indian cooking',
        'Knowledge of traditional cooking methods',
        'Experience with dosa, idli, and curry preparations',
        'Understanding of spice combinations',
        'Team collaboration skills'
      ],
      skills: ['South Indian Cooking', 'Traditional Methods', 'Spice Knowledge', 'Team Work'],
      jobType: 'FULL_TIME',
      experienceLevel: 'MID_LEVEL',
      salaryMin: 35000,
      salaryMax: 50000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Bangalore, Karnataka',
      workLocation: 'ON_SITE',
      benefits: ['Health Insurance', 'Staff Meals', 'Skill Development', 'Annual Bonus'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
      applicationsCount: 15,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    },
    {
      id: 'job-004',
      restaurantId: 'mock-restaurant-data-4',
      title: 'Restaurant Manager - Urban Bites',
      description: 'Seeking an experienced restaurant manager to oversee daily operations at Urban Bites. You will manage staff, ensure customer satisfaction, and drive business growth.',
      requirements: [
        '4+ years of restaurant management experience',
        'Strong leadership and communication skills',
        'Experience with P&L management',
        'Customer service excellence',
        'Knowledge of food safety regulations'
      ],
      skills: ['Management', 'Leadership', 'P&L Management', 'Customer Service', 'Operations'],
      jobType: 'FULL_TIME',
      experienceLevel: 'EXPERIENCED',
      salaryMin: 60000,
      salaryMax: 85000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Bangalore, Karnataka',
      workLocation: 'ON_SITE',
      benefits: ['Health Insurance', 'Performance Bonus', 'Paid Time Off', 'Staff Meals', 'Car Allowance'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
      applicationsCount: 6,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
      id: 'job-005',
      restaurantId: 'mock-restaurant-data-5',
      title: 'Traditional Cook - Maharashtrian Cuisine',
      description: 'Join our authentic Maharashtrian restaurant as a traditional cook. We value expertise in regional recipes and traditional cooking methods.',
      requirements: [
        'Expert knowledge of Maharashtrian cuisine',
        '2+ years of experience in traditional cooking',
        'Knowledge of regional ingredients',
        'Ability to maintain authenticity',
        'Dedication to quality'
      ],
      skills: ['Traditional Cooking', 'Regional Cuisine', 'Authenticity', 'Quality Control'],
      jobType: 'FULL_TIME',
      experienceLevel: 'MID_LEVEL',
      salaryMin: 28000,
      salaryMax: 40000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Pune, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Staff Meals', 'Festival Bonuses', 'Skills Training'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
      applicationsCount: 9,
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'job-006',
      restaurantId: 'mock-restaurant-data-6',
      title: 'Bartender - Fusion Delight',
      description: 'Looking for a creative bartender to join our Indo-Chinese fusion restaurant. Create signature cocktails and mocktails that complement our unique cuisine.',
      requirements: [
        '2+ years of bartending experience',
        'Knowledge of cocktail preparation',
        'Creative mindset for drink development',
        'Excellent customer interaction skills',
        'Understanding of Asian flavors preferred'
      ],
      skills: ['Bartending', 'Cocktail Creation', 'Customer Service', 'Creativity'],
      jobType: 'FULL_TIME',
      experienceLevel: 'MID_LEVEL',
      salaryMin: 25000,
      salaryMax: 35000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Pune, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Tips', 'Staff Meals', 'Creative Freedom', 'Performance Incentives'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
      applicationsCount: 11,
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'job-007',
      restaurantId: 'mock-restaurant-data-1',
      title: 'Kitchen Assistant - Best Burgers',
      description: 'Entry-level position perfect for someone starting their culinary career. Learn from experienced chefs while helping with food preparation and kitchen operations.',
      requirements: [
        'No prior experience required',
        'Willingness to learn',
        'Physical stamina for standing long hours',
        'Basic hygiene knowledge',
        'Team player attitude'
      ],
      skills: ['Food Preparation', 'Kitchen Operations', 'Hygiene', 'Team Work'],
      jobType: 'FULL_TIME',
      experienceLevel: 'ENTRY_LEVEL',
      salaryMin: 18000,
      salaryMax: 22000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Mumbai, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Staff Meals', 'Training', 'Career Growth', 'Flexible Hours'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
      applicationsCount: 23,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
    {
      id: 'job-008',
      restaurantId: 'mock-restaurant-data-4',
      title: 'Marketing Coordinator - Urban Bites',
      description: 'Join our marketing team to promote Urban Bites through digital channels, event planning, and customer engagement initiatives.',
      requirements: [
        '2+ years in marketing or related field',
        'Experience with social media marketing',
        'Event planning capabilities',
        'Strong communication skills',
        'Knowledge of restaurant industry preferred'
      ],
      skills: ['Digital Marketing', 'Social Media', 'Event Planning', 'Communication', 'Analytics'],
      jobType: 'FULL_TIME',
      experienceLevel: 'MID_LEVEL',
      salaryMin: 30000,
      salaryMax: 45000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Bangalore, Karnataka',
      workLocation: 'HYBRID',
      benefits: ['Health Insurance', 'Performance Bonus', 'Work From Home', 'Professional Development'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
      applicationsCount: 7,
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
    {
      id: 'job-009',
      restaurantId: 'mock-restaurant-data-2',
      title: 'Delivery Coordinator - Spice Garden',
      description: 'Manage delivery operations, coordinate with delivery partners, and ensure timely and accurate order fulfillment for our growing delivery business.',
      requirements: [
        '1+ years in logistics or operations',
        'Strong organizational skills',
        'Experience with delivery platforms',
        'Problem-solving abilities',
        'Computer literacy'
      ],
      skills: ['Logistics', 'Operations', 'Organization', 'Problem Solving', 'Technology'],
      jobType: 'FULL_TIME',
      experienceLevel: 'ENTRY_LEVEL',
      salaryMin: 24000,
      salaryMax: 32000,
      salaryCurrency: 'INR',
      salaryPeriod: 'MONTHLY',
      location: 'Mumbai, Maharashtra',
      workLocation: 'ON_SITE',
      benefits: ['Performance Incentives', 'Health Insurance', 'Staff Meals', 'Growth Opportunities'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
      applicationsCount: 14,
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: 'job-010',
      restaurantId: 'mock-restaurant-data-3',
      title: 'Part-time Cashier - Weekend Shifts',
      description: 'Perfect for students or those seeking part-time work. Handle customer payments, maintain cash register, and provide friendly service during our busy weekend periods.',
      requirements: [
        'High school education',
        'Basic math skills',
        'Customer service orientation',
        'Availability for weekends',
        'Honest and reliable'
      ],
      skills: ['Cash Handling', 'Customer Service', 'POS Systems', 'Math Skills'],
      jobType: 'PART_TIME',
      experienceLevel: 'ENTRY_LEVEL',
      salaryMin: 200,
      salaryMax: 250,
      salaryCurrency: 'INR',
      salaryPeriod: 'DAILY',
      location: 'Bangalore, Karnataka',
      workLocation: 'ON_SITE',
      benefits: ['Flexible Hours', 'Staff Meals', 'Weekend Premium'],
      status: 'ACTIVE',
      validTill: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
      applicationsCount: 18,
      createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    }
  ],

  // Job applications
  jobApplications: [
    {
      id: 'app-001',
      jobId: 'job-001',
      applicantId: 'mock-employee-1',
      status: 'APPLIED',
      resumeUrl: '/resumes/employee-1-resume.pdf',
      coverLetter: 'I am excited to apply for the Head Chef position at Best Burgers. With over 6 years of experience in kitchen management and a passion for creating exceptional food experiences, I believe I would be a great fit for your team.',
      expectedSalary: 65000,
      availableFromDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
      applicationAnswers: [
        {
          question: 'Do you have experience with American cuisine?',
          answer: 'Yes, I have worked in American-style restaurants for 4 years.'
        },
        {
          question: 'Are you available for weekend shifts?',
          answer: 'Yes, I am flexible with my schedule including weekends.'
        }
      ],
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    }
  ],

  // Employee schedules
  schedules: [
    {
      id: 'schedule-001',
      employeeId: 'mock-employee-1',
      restaurantId: 'mock-restaurant-data-1',
      shift: 'MORNING',
      date: new Date(),
      startTime: '08:00',
      endTime: '16:00',
      position: 'Chef',
      status: 'SCHEDULED',
      notes: 'Kitchen prep and lunch service',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'schedule-002',
      employeeId: 'mock-employee-1',
      restaurantId: 'mock-restaurant-data-1',
      shift: 'EVENING',
      date: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
      startTime: '16:00',
      endTime: '00:00',
      position: 'Chef',
      status: 'SCHEDULED',
      notes: 'Dinner service and kitchen cleanup',
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Payment methods and wallet data
  paymentMethods: [
    {
      id: 'pm-001',
      userId: 'mock-customer-1',
      type: 'CARD',
      provider: 'VISA',
      lastFourDigits: '4532',
      expiryMonth: 12,
      expiryYear: 2025,
      cardHolderName: 'Valued Customer',
      isDefault: true,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'pm-002',
      userId: 'mock-customer-1',
      type: 'UPI',
      provider: 'PAYTM',
      upiId: 'customer@paytm',
      isDefault: false,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],

  // Wallet transactions
  walletTransactions: [
    {
      id: 'wallet-001',
      userId: 'mock-customer-1',
      type: 'CREDIT',
      amount: 500.00,
      description: 'Cashback from order #ORD-20240313-001',
      referenceId: 'order-001',
      status: 'COMPLETED',
      balanceBefore: 1000.00,
      balanceAfter: 1500.00,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: 'wallet-002',
      userId: 'mock-customer-1',
      type: 'DEBIT',
      amount: 300.00,
      description: 'Payment for order #ORD-20240313-002',
      referenceId: 'order-002',
      status: 'COMPLETED',
      balanceBefore: 1500.00,
      balanceAfter: 1200.00,
      createdAt: new Date(Date.now() - 30 * 60 * 1000),
      updatedAt: new Date(Date.now() - 30 * 60 * 1000),
    },
    {
      id: 'wallet-003',
      userId: 'mock-customer-2',
      type: 'CREDIT',
      amount: 1000.00,
      description: 'Welcome bonus for new users',
      referenceId: null,
      status: 'COMPLETED',
      balanceBefore: 0.00,
      balanceAfter: 1000.00,
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'wallet-004',
      userId: 'mock-customer-2',
      type: 'DEBIT',
      amount: 914.00,
      description: 'Payment for order #ORD-20240313-002',
      referenceId: 'order-002',
      status: 'COMPLETED',
      balanceBefore: 1000.00,
      balanceAfter: 86.00,
      createdAt: new Date(Date.now() - 15 * 60 * 1000),
      updatedAt: new Date(Date.now() - 15 * 60 * 1000),
    },
    {
      id: 'wallet-005',
      userId: 'mock-customer-3',
      type: 'CREDIT',
      amount: 200.00,
      description: 'Referral bonus for inviting friends',
      referenceId: 'ref-bonus',
      status: 'COMPLETED',
      balanceBefore: 500.00,
      balanceAfter: 700.00,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'wallet-006',
      userId: 'mock-customer-4',
      type: 'CREDIT',
      amount: 50000.00,
      description: 'Corporate account top-up',
      referenceId: 'corp-topup-001',
      status: 'COMPLETED',
      balanceBefore: 5000.00,
      balanceAfter: 55000.00,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'wallet-007',
      userId: 'mock-customer-5',
      type: 'DEBIT',
      amount: 1210.00,
      description: 'Refund processed for cancelled order #ORD-20240313-006',
      referenceId: 'order-006',
      status: 'COMPLETED',
      balanceBefore: 800.00,
      balanceAfter: 2010.00,
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    }
  ],

  // Analytics data
  analytics: {
    restaurantDashboard: {
      todaysOrders: 15,
      todaysRevenue: 12500.00,
      weeklyOrders: 89,
      weeklyRevenue: 67500.00,
      monthlyOrders: 342,
      monthlyRevenue: 256890.00,
      topSellingItems: [
        { name: 'Classic Burger', quantity: 156, revenue: 54600 },
        { name: 'French Fries', quantity: 134, revenue: 20100 },
        { name: 'Chicken Wings', quantity: 98, revenue: 34300 }
      ],
      peakHours: [
        { hour: '12:00-13:00', orders: 28 },
        { hour: '19:00-20:00', orders: 35 },
        { hour: '20:00-21:00', orders: 42 }
      ]
    },
    vendorDashboard: {
      todaysOrders: 8,
      todaysRevenue: 5600.00,
      weeklyOrders: 45,
      weeklyRevenue: 32500.00,
      monthlyOrders: 178,
      monthlyRevenue: 125600.00,
      topSellingProducts: [
        { name: 'Premium Tomatoes', quantity: 245, revenue: 11025 },
        { name: 'Garam Masala Powder', quantity: 67, revenue: 18760 },
        { name: 'Fresh Onions', quantity: 189, revenue: 6615 }
      ]
    },
    adminDashboard: {
      totalUsers: 1256,
      totalRestaurants: 89,
      totalVendors: 45,
      totalOrders: 5678,
      totalRevenue: 1234567.89,
      growthMetrics: {
        usersGrowth: 12.5, // percentage
        ordersGrowth: 8.3,
        revenueGrowth: 15.2
      }
    }
  },

  // Reviews and ratings
  reviews: [
    {
      id: 'review-001',
      userId: 'mock-customer-1',
      targetId: 'mock-restaurant-data-1',
      targetType: 'RESTAURANT',
      orderId: 'order-001',
      rating: 5,
      title: 'Excellent food and service!',
      content: 'Had an amazing dining experience at Best Burgers. The food was delicious, service was prompt, and the ambiance was perfect for our anniversary dinner. Highly recommended!',
      images: [],
      isVerifiedPurchase: true,
      helpfulCount: 3,
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
    {
      id: 'review-002',
      userId: 'mock-customer-1',
      targetId: 'prod-001',
      targetType: 'PRODUCT',
      orderId: 'order-002',
      rating: 5,
      title: 'Fresh and high quality tomatoes',
      content: 'The tomatoes were very fresh and perfect for cooking. Delivered on time and well packaged. Will definitely order again!',
      images: [],
      isVerifiedPurchase: true,
      helpfulCount: 2,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    }
  ],

  // Notifications
  notifications: [
    {
      id: 'notif-001',
      userId: 'mock-restaurant-1',
      title: 'New Order Received',
      message: 'You have received a new order #ORD-20240313-001 from Valued Customer',
      type: 'ORDER',
      data: {
        orderId: 'order-001',
        orderNumber: 'ORD-20240313-001'
      },
      isRead: false,
      createdAt: new Date(Date.now() - 30 * 60 * 1000),
    },
    {
      id: 'notif-002',
      userId: 'mock-customer-1',
      title: 'Order Completed',
      message: 'Your order #ORD-20240313-001 has been completed. Enjoy your meal!',
      type: 'ORDER',
      data: {
        orderId: 'order-001',
        orderNumber: 'ORD-20240313-001'
      },
      isRead: true,
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    }
  ],

  // Sessions (for authentication)
  sessions: []
};

export default mockData;